language: ruby
cache: bundler
sudo: true

rvm:
  - 2.2
  #- 2.1
  #- 1.9.3

matrix:
  include:
    #- rvm: 2.2
    - rvm: 2.1
    - rvm: 1.9.3

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - sudo apt-get install -y libmysqlclient-dev
  - bundle exec rake hyacinth:test:setup_config_files_for_test_environment
  
script: bundle exec rake hyacinth:ci