language: ruby
cache: bundler
sudo: false

rvm:
  - 2.1
  
jdk: 'oraclejdk8'

matrix:
  include:
    - rvm: 1.9.3

notifications:
  irc: "irc.freenode.org#ldpddev"

env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true

before_script:
  - bundle exec rake hyacinth:test:setup_config_files_for_test_environment
  
script: bundle exec rake hyacinth:ci